### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by haftado3** [lirios/cmake-shared#1]
i think making in windows  is only possible with `cmake -G "Unix Makefiles" ..`, i  couldnt make `-G "NMake Makefiles"` nmake gives this error : 

> Extension(s) (.PHONY) not defined

**Comment by plfiorini** [comment]
You can also use Visual Studio with `cmake -G "Visual Studio 14 2015"`, see https://github.com/lirios/fluid/blob/develop/.appveyor.yml
However `cmake -G "Visual Studio 15 2017"` gave build errors while it was working with `qbs` before.
